/****************************************************************************
**
** Copyright (C) 2020 The ZHIZUO Company Ltd.
**
** This file is part of the ZHIZUO Ultrasound SDK.
**
** Private License
** All right include copy change are reserved.
**
****************************************************************************/


#include "ctrltableutil.h"

CtrlTableUtil::CtrlTableUtil() {
}

configuru::Config CtrlTableUtil::GetFromCtrlTable(const pipeline_fpga_table &table_in) {
  configuru::Config cfg_dev_fpga {
    /* offset 0  */
    /* blank for 8 bits : 8 */
    {"blk_0", int(table_in.blk_0)},

    /* offset 1  */
    /*B型多波束:3*/
    {"ARGS_B_MULTIPLE_BEAM", int(table_in.ARGS_B_MULTIPLE_BEAM)},
    /*C型多波束:3*/
    {"ARGS_C_MULTIPLE_BEAM", int(table_in.ARGS_C_MULTIPLE_BEAM)},
    /*壁滤波D:2*/
    {"ARGS_D_WALLFILTER", int(table_in.ARGS_D_WALLFILTER)},

    /* offset 2  */
    /*累计次数:4*/
    {"ARGS_C_ACCUMULATION", int(table_in.ARGS_C_ACCUMULATION)},
    /*动态范围:4*/
    {"ARGS_B_RANGE", (int)(table_in.ARGS_B_RANGE)},

    /* offset 3  */
    /*血流多普勒采样间隔倍数:5*/
    {"ARGS_SAMPLING_INTERVAL", int(table_in.ARGS_SAMPLING_INTERVAL)},
    /*壁滤波C:2*/
    {"ARGS_C_FILTER", int(table_in.ARGS_C_FILTER)},
    /*CPA:1*/
    {"ARGS_CPA", int(table_in.ARGS_CPA)},

    /*offset 4*/
    /*BM型发射频率分频比:6*/
    {"ARGS_BM_FREQUENCY_DIVISION_RATIO", int(table_in.ARGS_BM_FREQUENCY_DIVISION_RATIO)},
    /*宽带:1*/
    {"ARGS_WIDE_BAND", int(table_in.ARGS_WIDE_BAND)},
    /*冻结:1*/
    {"ARGS_FREEZE", int(table_in.ARGS_FREEZE)},
    /*offset 5*/
    /*发射焦点深度:4*/
    {"ARGS_FOCAL_DEPTH",int(table_in.ARGS_FOCAL_DEPTH)},
    /*M:1*/
    {"ARGS_M",int(table_in.ARGS_M)},
    /*D:1*/
    {"ARGS_D",int(table_in.ARGS_D)},
    /*C:1*/
    {"ARGS_C",int(table_in.ARGS_C)},
    /*B:1*/
    {"ARGS_B",int(table_in.ARGS_B)},

    /*offset 6*/
    /*BM型接收频率分频比:6*/
    {"ARGS_BM_RECEIVER_FREQUENCY_RATIO",int(table_in.ARGS_BM_RECEIVER_FREQUENCY_RATIO)},
    /*谐波1:1*/
    {"ARGS_B_HARMONIC_1",int(table_in.ARGS_B_HARMONIC_1)},
    /*谐波2:1*/
    {"ARGS_B_HARMONIC_2",int(table_in.ARGS_B_HARMONIC_2)},

    /*offset 7*/
    /*C型起发线号:7*/
    {"ARGS_C_SCAN_START", int(table_in.ARGS_C_SCAN_START)},
    /*:1*/
    {"ARGS_KEY_MODE", int(table_in.ARGS_KEY_MODE)},
    /*c type start line number*/
    {"ARGS_C_SCAN_END", int(table_in.ARGS_C_SCAN_END)},
    /*:1*/
    {"blk_2",int(table_in.blk_2)},

    /*offset 9*/
    /*探头类型编码:3*/
    {"ARGS_PROBE_SOFT_CODE",int(table_in.ARGS_PROBE_SOFT_CODE)},
    /*线阵偏转角度:5*/
    {"ARGS_LINEAR_DEFLECTION_ANGLE",int(table_in.ARGS_LINEAR_DEFLECTION_ANGLE)},

    /*offset 10*/
    /*B总增益:8*/
    {"ARGS_B_GAIN", int(table_in.ARGS_B_GAIN)},

    /*offset 11*/
    /*八段TGC之1:8*/
    {"ARGS_TGC_1", int(table_in.ARGS_TGC_1)},

    /*offset 12*/
    /*八段TGC之2*/
    {"ARGS_TGC_2", int(table_in.ARGS_TGC_2)},

    /*offset 13*/
    /*八段TGC之3*/
    {"ARGS_TGC_3", int(table_in.ARGS_TGC_3)},

    /*offset 14*/
    /*八段TGC之4*/
    {"ARGS_TGC_4", int(table_in.ARGS_TGC_4)},

    /*offset 15*/
    /*八段TGC之5*/
    {"ARGS_TGC_5", int(table_in.ARGS_TGC_5)},

    /*offset 16*/
    /*八段TGC之6*/
    {"ARGS_TGC_6", int(table_in.ARGS_TGC_6)},

    /*offset 17*/
    /*八段TGC之7*/
    {"ARGS_TGC_7", int(table_in.ARGS_TGC_7)},

    /*offset 18*/
    /*八段TGC之8*/
    {"ARGS_TGC_8", int(table_in.ARGS_TGC_8)},

    /*offset 19*/
    /*C总增益:8*/
    {"ARGS_C_GAIN", int(table_in.ARGS_C_GAIN)},

    /*offset 20*/
    /*声功率选择:4*/
    {"ARGS_SOUND_POWER", int(table_in.ARGS_SOUND_POWER)},
    /*识别码选择:2*/
    {"ARGS_ID", int(table_in.ARGS_ID)},
    /*探头选择:2*/
    {"ARGS_PROBE", int(table_in.ARGS_PROBE)},

    /*offset 21*/
    /*C型抽取因子:5*/
    {"ARGS_C_FACTOR", int(table_in.ARGS_C_FACTOR)},
    /*B型发射线号步进:3*/
    {"ARGS_B_STEP", int(table_in.ARGS_B_STEP)},

    /*offset 22*/
    /*血流窗口起始深度xcws低8位:8*/
    {"ARGS_XCWS_LOW_8",int(table_in.ARGS_XCWS_LOW_8)},

    /*offset 23*/
    /*多普勒采样深度xdws高4位:4*/
    {"ARGS_XDWS_HIGH_4",int(table_in.ARGS_XDWS_HIGH_4)},

    /*血流窗口起始深度xcws高4位:4*/
    {"ARGS_XCWS_HIGH_4",int(table_in.ARGS_XCWS_HIGH_4)},


    /*offset 24*/
    /*多普勒采样深度xdws低8位:8*/
    {"ARGS_XDWS_LOW_8",int(table_in.ARGS_XDWS_LOW_8)},

    /*offset 25 */
    /*频谱多普勒采样间隔:4*/
    {"ARGS_D_SAMPLING_INTERVAL",int(table_in.ARGS_D_SAMPLING_INTERVAL)},
    /*M/D模式速度:3*/
    {"ARGS_M_D_SPEED",int(table_in.ARGS_M_D_SPEED)},
    /*BCD/D:1*/
    {"ARGS_BCD_OR_D",int(table_in.ARGS_BCD_OR_D)},

    /*offset 26*/
    /*MD发射线号:7*/
    {"ARGS_MD_LINE",int(table_in.ARGS_MD_LINE)},
    /*:1*/
    {"blk_3",int(table_in.blk_3)},

    /*offset 27*/
    /*C型发射频率分频比:6*/
    {"ARGS_C_FREQUENCY_DIVISION_RATIO",int(table_in.ARGS_C_FREQUENCY_DIVISION_RATIO)},
    /*发射电流:2*/
    {"ARGS_FREQUENCY_CURRENT",int(table_in.ARGS_FREQUENCY_CURRENT)},

    /*offset 28*/
    /*B型抽取因子:5*/
    {"ARGS_B_FACTOR",int(table_in.ARGS_B_FACTOR)},
    /*多普勒采样容积:3*/
    {"ARGS_D_SAMPLING",int(table_in.ARGS_D_SAMPLING)},

    /*offset 29*/
    /*速度阈值:5*/
    {"ARGS_SPEED_THRESHOLD",int(table_in.ARGS_SPEED_THRESHOLD)},
    /*权重:3*/
    {"ARGS_WEIGHT",int(table_in.ARGS_WEIGHT)},


    /*offset 30*/
    /*幅度阈值:5*/
    {"ARGS_RANGE_THRESHOLD",int(table_in.ARGS_RANGE_THRESHOLD)},
    /*5805配置:3*/
    {"ARGS_5805_CONFIG",int(table_in.ARGS_5805_CONFIG)},

    /*offset 31*/
    /*M总增益:8*/
    {"ARGS_M_GAIN",int(table_in.ARGS_M_GAIN)},

    /*offset 32*/
    /*D总增益:8*/
    {"ARGS_D_GAIN",int(table_in.ARGS_D_GAIN)},

    /*offset 33*/
    /*D型发射频率分频比:6*/
    {"ARGS_D_TRANSMISSIONFREQUENCY",int(table_in.ARGS_D_TRANSMISSIONFREQUENCY)},
    /*:2*/
    {"blk_4",int(table_in.blk_4)},

    /*offset 34*/
    /*串行发射功率:8*/
    {"ARGS_SERIAL_POWER",int(table_in.ARGS_SERIAL_POWER)},

    /*offset 35*/
    /*:8*/
    {"blk_5",int(table_in.blk_5)},

    /*offset 36:7*/
    /*声速选择*/
    {"ARGS_SOUND_SPEED",int(table_in.ARGS_SOUND_SPEED)},
    /*: 1*/
    {"ARGS_CONTRAST_MODE",int(table_in.ARGS_CONTRAST_MODE)},

    /*offset 37*/
    /*模拟TGC之1:8*/
    {"ARGS_A_TGC_1",int(table_in.ARGS_A_TGC_1)},

    /*offset 38*/
    /*模拟TGC之2*/
    {"ARGS_A_TGC_2",int(table_in.ARGS_A_TGC_2)},

    /*offset 39*/
    /*模拟TGC之3*/
    {"ARGS_A_TGC_3",int(table_in.ARGS_A_TGC_3)},

    /*offset 40*/
    /*模拟TGC之4*/
    {"ARGS_A_TGC_4",int(table_in.ARGS_A_TGC_4)},

    /*offset 41*/
    /*模拟TGC之5*/
    {"ARGS_A_TGC_5",int(table_in.ARGS_A_TGC_5)},

    /*offset 42*/
    /*模拟TGC之6*/
    {"ARGS_A_TGC_6",int(table_in.ARGS_A_TGC_6)},

    /*offset 43*/
    /*模拟TGC之7*/
    {"ARGS_A_TGC_7",int(table_in.ARGS_A_TGC_7)},

    /*offset 44*/
    /*模拟TGC之8*/
    {"ARGS_A_TGC_8",int(table_in.ARGS_A_TGC_8)},

    /*offset 45*/
    /*数字TGC之1:8*/
    {"ARGS_B_TGC_1",int(table_in.ARGS_B_TGC_1)},

    /*offset 46*/
    /*数字TGC之2*/
    {"ARGS_B_TGC_2",int(table_in.ARGS_B_TGC_2)},

    /*offset 47*/
    /*数字TGC之3*/
    {"ARGS_B_TGC_3",int(table_in.ARGS_B_TGC_3)},

    /*offset 48*/
    /*数字TGC之4*/
    {"ARGS_B_TGC_4",int(table_in.ARGS_B_TGC_4)},

    /*offset 49*/
    /*数字TGC之5*/
    {"ARGS_B_TGC_5",int(table_in.ARGS_B_TGC_5)},

    /*offset 50*/
    /*数字TGC之6*/
    {"ARGS_B_TGC_6",int(table_in.ARGS_B_TGC_6)},

    /*offset 51*/
    /*数字TGC之7*/
    {"ARGS_B_TGC_7",int(table_in.ARGS_B_TGC_7)},

    /*offset 52*/
    /*数字TGC之8*/
    {"ARGS_B_TGC_8",int(table_in.ARGS_B_TGC_8)},

    /*offset 53*/
    /*C型发射焦点深度:4*/
    {"ARGS_C_TRANSMIT_FOCUS",int(table_in.ARGS_C_TRANSMIT_FOCUS)},
    /*B型发射焦点深度:4*/
    {"ARGS_B_TRANSMIT_FOCUS",int(table_in.ARGS_B_TRANSMIT_FOCUS)},

    /*offset 54*/
    /*血流窗上边:8*/
    {"ARGS_C_FRAME_UP",int(table_in.ARGS_C_FRAME_UP)},

    /*offset 55*/
    /*血流窗下边:8*/
    {"ARGS_C_FRAME_DOWN",int(table_in.ARGS_C_FRAME_DOWN)},

    /*offset 56*/
    /*什么鬼:8*/
    {"blk_7",int(table_in.blk_7)},

    /*offset 57*/
    /*什么鬼:8*/
    {"blk_8",int(table_in.blk_8)},

    /*=======硬件信息地址:8=========*/
    {"ARGS_RestTime",int(table_in.ARGS_RestTime)},

    /*offset 59*/
    /*TCP或UDP块数:8*/
    {"ARGS_UDP_OR_TCP_NUMBER",int(table_in.ARGS_UDP_OR_TCP_NUMBER)},

    /*offset 60*/
    /*归位:1*/
    {"ARGS_RESET",int(table_in.ARGS_RESET)},
    /*启停:1*/
    {"ARGS_START",int(table_in.ARGS_START)},
    /*体分辨率:2*/
    {"ARGS_TI",int(table_in.ARGS_TI)},
    /*电机类型:2*/
    {"ARGS_MOTOR_TYPE",int(table_in.ARGS_MOTOR_TYPE)},
    /*:2*/
    {"blk_10",int(table_in.blk_10)},

    /*offset 61*/
    /*硬件信息地址:8*/
    {"blk_11",int(table_in.blk_11)},

    /*offset 62*/
    /*绿LED:1*/
    {"ARGS_GREEN_LED",int(table_in.ARGS_GREEN_LED)},
    /*红LED:1*/
    {"ARGS_RED_LED",int(table_in.ARGS_RED_LED)},
    /*:1*/
    {"ARGS_IDLE",int(table_in.ARGS_IDLE)},
    /*:1*/
    {"ARGS_OFF",int(table_in.ARGS_OFF)},
    /*:1*/
    {"ARGS_US_CHG",int(table_in.ARGS_US_CHG)},
    /*USB_IF:1*/
    {"ARGS_USB_IF",int(table_in.ARGS_USB_IF)},
    /*WIFI_IF:1*/
    {"ARGS_WIFI_IF",int(table_in.ARGS_WIFI_IF)},
    /*OTA:1*/
    {"ARGS_OTA",int(table_in.ARGS_OTA)},
    /*offset 63*/
    /*:8*/
    {"blk_15",int(table_in.blk_15)}
  };
  return cfg_dev_fpga;
}

pipeline_fpga_table CtrlTableUtil::GetFromConfigTable(const pipeline_fpga_table &src, const configuru::Config &cfg_table) {
  pipeline_fpga_table fpga_table = {0};
#define CTRLTABLE_FROM_CFG_ITEM(item, arg2) fpga_table.item=(unsigned char)(cfg_table.has_key(arg2) ? cfg_table[arg2] : src.item);
  CTRLTABLE_FROM_CFG_ITEM(blk_0, "blk_0")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_MULTIPLE_BEAM, "ARGS_B_MULTIPLE_BEAM")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_MULTIPLE_BEAM, "ARGS_C_MULTIPLE_BEAM")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_D_WALLFILTER, "ARGS_D_WALLFILTER")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_ACCUMULATION, "ARGS_C_ACCUMULATION")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_RANGE, "ARGS_B_RANGE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_SAMPLING_INTERVAL, "ARGS_SAMPLING_INTERVAL")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_FILTER, "ARGS_C_FILTER")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_CPA, "ARGS_CPA")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_BM_FREQUENCY_DIVISION_RATIO, "ARGS_BM_FREQUENCY_DIVISION_RATIO")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_WIDE_BAND, "ARGS_WIDE_BAND")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_FREEZE, "ARGS_FREEZE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_FOCAL_DEPTH, "ARGS_FOCAL_DEPTH")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_M, "ARGS_M")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_D, "ARGS_D")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C, "ARGS_C")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B, "ARGS_B")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_BM_RECEIVER_FREQUENCY_RATIO, "ARGS_BM_RECEIVER_FREQUENCY_RATIO")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_HARMONIC_1, "ARGS_B_HARMONIC_1")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_HARMONIC_2, "ARGS_B_HARMONIC_2")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_SCAN_START, "ARGS_C_SCAN_START")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_KEY_MODE, "ARGS_KEY_MODE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_SCAN_END, "ARGS_C_SCAN_END")
  CTRLTABLE_FROM_CFG_ITEM(blk_2, "blk_2")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_PROBE_SOFT_CODE, "ARGS_PROBE_SOFT_CODE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_LINEAR_DEFLECTION_ANGLE, "ARGS_LINEAR_DEFLECTION_ANGLE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_GAIN, "ARGS_B_GAIN")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_1, "ARGS_TGC_1")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_2, "ARGS_TGC_2")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_3, "ARGS_TGC_3")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_4, "ARGS_TGC_4")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_5, "ARGS_TGC_5")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_6, "ARGS_TGC_6")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_7, "ARGS_TGC_7")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_8, "ARGS_TGC_8")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_GAIN, "ARGS_C_GAIN")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_SOUND_POWER, "ARGS_SOUND_POWER")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_ID, "ARGS_ID")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_PROBE, "ARGS_PROBE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_FACTOR, "ARGS_C_FACTOR")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_STEP, "ARGS_B_STEP")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_XCWS_LOW_8, "ARGS_XCWS_LOW_8")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_XDWS_HIGH_4, "ARGS_XDWS_HIGH_4")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_XCWS_HIGH_4, "ARGS_XCWS_HIGH_4")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_XDWS_LOW_8, "ARGS_XDWS_LOW_8")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_D_SAMPLING_INTERVAL, "ARGS_D_SAMPLING_INTERVAL")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_M_D_SPEED, "ARGS_M_D_SPEED")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_BCD_OR_D, "ARGS_BCD_OR_D")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_MD_LINE, "ARGS_MD_LINE")
  CTRLTABLE_FROM_CFG_ITEM(blk_3, "blk_3")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_FREQUENCY_DIVISION_RATIO, "ARGS_C_FREQUENCY_DIVISION_RATIO")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_FREQUENCY_CURRENT, "ARGS_FREQUENCY_CURRENT")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_FACTOR, "ARGS_B_FACTOR")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_D_SAMPLING, "ARGS_D_SAMPLING")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_SPEED_THRESHOLD, "ARGS_SPEED_THRESHOLD")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_WEIGHT, "ARGS_WEIGHT")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_RANGE_THRESHOLD, "ARGS_RANGE_THRESHOLD")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_5805_CONFIG, "ARGS_5805_CONFIG")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_M_GAIN, "ARGS_M_GAIN")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_D_GAIN, "ARGS_D_GAIN")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_D_TRANSMISSIONFREQUENCY, "ARGS_D_TRANSMISSIONFREQUENCY")
  CTRLTABLE_FROM_CFG_ITEM(blk_4, "blk_4")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_SERIAL_POWER, "ARGS_SERIAL_POWER")
  CTRLTABLE_FROM_CFG_ITEM(blk_5, "blk_5")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_SOUND_SPEED, "ARGS_SOUND_SPEED")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_CONTRAST_MODE, "ARGS_CONTRAST_MODE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_1, "ARGS_A_TGC_1")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_2, "ARGS_A_TGC_2")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_3, "ARGS_A_TGC_3")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_4, "ARGS_A_TGC_4")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_5, "ARGS_A_TGC_5")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_6, "ARGS_A_TGC_6")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_7, "ARGS_A_TGC_7")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_8, "ARGS_A_TGC_8")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_1, "ARGS_B_TGC_1")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_2, "ARGS_B_TGC_2")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_3, "ARGS_B_TGC_3")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_4, "ARGS_B_TGC_4")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_5, "ARGS_B_TGC_5")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_6, "ARGS_B_TGC_6")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_7, "ARGS_B_TGC_7")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_8, "ARGS_B_TGC_8")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_TRANSMIT_FOCUS, "ARGS_C_TRANSMIT_FOCUS")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TRANSMIT_FOCUS, "ARGS_B_TRANSMIT_FOCUS")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_FRAME_UP, "ARGS_C_FRAME_UP")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_FRAME_DOWN, "ARGS_C_FRAME_DOWN")
  CTRLTABLE_FROM_CFG_ITEM(blk_7, "blk_7")
  CTRLTABLE_FROM_CFG_ITEM(blk_8, "blk_8")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_RestTime, "ARGS_RestTime")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_UDP_OR_TCP_NUMBER, "ARGS_UDP_OR_TCP_NUMBER")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_RESET, "ARGS_RESET")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_START, "ARGS_START")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TI, "ARGS_TI")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_MOTOR_TYPE, "ARGS_MOTOR_TYPE")
  CTRLTABLE_FROM_CFG_ITEM(blk_10, "blk_10")
  CTRLTABLE_FROM_CFG_ITEM(blk_11, "blk_11")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_GREEN_LED, "ARGS_GREEN_LED")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_RED_LED, "ARGS_RED_LED")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_IDLE, "ARGS_IDLE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_OFF, "ARGS_OFF")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_US_CHG, "ARGS_US_CHG")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_USB_IF, "ARGS_USB_IF")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_WIFI_IF, "ARGS_WIFI_IF")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_OTA, "ARGS_OTA")
  CTRLTABLE_FROM_CFG_ITEM(blk_15, "blk_15")

#undef CTRLTABLE_FROM_CFG_ITEM(item, arg2)
  return fpga_table;
}

pipeline_fpga_table CtrlTableUtil::GetFromConfigTable(const configuru::Config &cfg_table) {
  pipeline_fpga_table fpga_table = {0};
#define CTRLTABLE_FROM_CFG_ITEM(item, arg2) fpga_table.item=(unsigned char)(cfg_table[arg2]);
  CTRLTABLE_FROM_CFG_ITEM(blk_0, "blk_0")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_MULTIPLE_BEAM, "ARGS_B_MULTIPLE_BEAM")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_MULTIPLE_BEAM, "ARGS_C_MULTIPLE_BEAM")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_D_WALLFILTER, "ARGS_D_WALLFILTER")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_ACCUMULATION, "ARGS_C_ACCUMULATION")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_RANGE, "ARGS_B_RANGE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_SAMPLING_INTERVAL, "ARGS_SAMPLING_INTERVAL")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_FILTER, "ARGS_C_FILTER")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_CPA, "ARGS_CPA")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_BM_FREQUENCY_DIVISION_RATIO, "ARGS_BM_FREQUENCY_DIVISION_RATIO")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_WIDE_BAND, "ARGS_WIDE_BAND")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_FREEZE, "ARGS_FREEZE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_FOCAL_DEPTH, "ARGS_FOCAL_DEPTH")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_M, "ARGS_M")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_D, "ARGS_D")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C, "ARGS_C")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B, "ARGS_B")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_BM_RECEIVER_FREQUENCY_RATIO, "ARGS_BM_RECEIVER_FREQUENCY_RATIO")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_HARMONIC_1, "ARGS_B_HARMONIC_1")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_HARMONIC_2, "ARGS_B_HARMONIC_2")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_SCAN_START, "ARGS_C_SCAN_START")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_KEY_MODE, "ARGS_KEY_MODE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_SCAN_END, "ARGS_C_SCAN_END")
  CTRLTABLE_FROM_CFG_ITEM(blk_2, "blk_2")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_PROBE_SOFT_CODE, "ARGS_PROBE_SOFT_CODE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_LINEAR_DEFLECTION_ANGLE, "ARGS_LINEAR_DEFLECTION_ANGLE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_GAIN, "ARGS_B_GAIN")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_1, "ARGS_TGC_1")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_2, "ARGS_TGC_2")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_3, "ARGS_TGC_3")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_4, "ARGS_TGC_4")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_5, "ARGS_TGC_5")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_6, "ARGS_TGC_6")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_7, "ARGS_TGC_7")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TGC_8, "ARGS_TGC_8")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_GAIN, "ARGS_C_GAIN")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_SOUND_POWER, "ARGS_SOUND_POWER")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_ID, "ARGS_ID")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_PROBE, "ARGS_PROBE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_FACTOR, "ARGS_C_FACTOR")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_STEP, "ARGS_B_STEP")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_XCWS_LOW_8, "ARGS_XCWS_LOW_8")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_XDWS_HIGH_4, "ARGS_XDWS_HIGH_4")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_XCWS_HIGH_4, "ARGS_XCWS_HIGH_4")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_XDWS_LOW_8, "ARGS_XDWS_LOW_8")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_D_SAMPLING_INTERVAL, "ARGS_D_SAMPLING_INTERVAL")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_M_D_SPEED, "ARGS_M_D_SPEED")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_BCD_OR_D, "ARGS_BCD_OR_D")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_MD_LINE, "ARGS_MD_LINE")
  CTRLTABLE_FROM_CFG_ITEM(blk_3, "blk_3")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_FREQUENCY_DIVISION_RATIO, "ARGS_C_FREQUENCY_DIVISION_RATIO")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_FREQUENCY_CURRENT, "ARGS_FREQUENCY_CURRENT")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_FACTOR, "ARGS_B_FACTOR")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_D_SAMPLING, "ARGS_D_SAMPLING")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_SPEED_THRESHOLD, "ARGS_SPEED_THRESHOLD")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_WEIGHT, "ARGS_WEIGHT")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_RANGE_THRESHOLD, "ARGS_RANGE_THRESHOLD")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_5805_CONFIG, "ARGS_5805_CONFIG")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_M_GAIN, "ARGS_M_GAIN")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_D_GAIN, "ARGS_D_GAIN")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_D_TRANSMISSIONFREQUENCY, "ARGS_D_TRANSMISSIONFREQUENCY")
  CTRLTABLE_FROM_CFG_ITEM(blk_4, "blk_4")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_SERIAL_POWER, "ARGS_SERIAL_POWER")
  CTRLTABLE_FROM_CFG_ITEM(blk_5, "blk_5")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_SOUND_SPEED, "ARGS_SOUND_SPEED")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_CONTRAST_MODE, "ARGS_CONTRAST_MODE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_1, "ARGS_A_TGC_1")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_2, "ARGS_A_TGC_2")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_3, "ARGS_A_TGC_3")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_4, "ARGS_A_TGC_4")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_5, "ARGS_A_TGC_5")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_6, "ARGS_A_TGC_6")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_7, "ARGS_A_TGC_7")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_A_TGC_8, "ARGS_A_TGC_8")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_1, "ARGS_B_TGC_1")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_2, "ARGS_B_TGC_2")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_3, "ARGS_B_TGC_3")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_4, "ARGS_B_TGC_4")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_5, "ARGS_B_TGC_5")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_6, "ARGS_B_TGC_6")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_7, "ARGS_B_TGC_7")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TGC_8, "ARGS_B_TGC_8")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_TRANSMIT_FOCUS, "ARGS_C_TRANSMIT_FOCUS")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_B_TRANSMIT_FOCUS, "ARGS_B_TRANSMIT_FOCUS")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_FRAME_UP, "ARGS_C_FRAME_UP")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_C_FRAME_DOWN, "ARGS_C_FRAME_DOWN")
  CTRLTABLE_FROM_CFG_ITEM(blk_7, "blk_7")
  CTRLTABLE_FROM_CFG_ITEM(blk_8, "blk_8")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_RestTime, "ARGS_RestTime")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_UDP_OR_TCP_NUMBER, "ARGS_UDP_OR_TCP_NUMBER")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_RESET, "ARGS_RESET")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_START, "ARGS_START")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_TI, "ARGS_TI")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_MOTOR_TYPE, "ARGS_MOTOR_TYPE")
  CTRLTABLE_FROM_CFG_ITEM(blk_10, "blk_10")
  CTRLTABLE_FROM_CFG_ITEM(blk_11, "blk_11")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_GREEN_LED, "ARGS_GREEN_LED")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_RED_LED, "ARGS_RED_LED")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_IDLE, "ARGS_IDLE")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_OFF, "ARGS_OFF")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_US_CHG, "ARGS_US_CHG")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_USB_IF, "ARGS_USB_IF")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_WIFI_IF, "ARGS_WIFI_IF")
  CTRLTABLE_FROM_CFG_ITEM(ARGS_OTA, "ARGS_OTA")
  CTRLTABLE_FROM_CFG_ITEM(blk_15, "blk_15")

#undef CTRLTABLE_FROM_CFG_ITEM(item, arg2)
  return fpga_table;
}
